### ISSUE TITLE
尾崎さん共有用

### ISSUE THREAD

**Issue by YNSTakeru** [apprentice-team-3/team-weekly-report#326]

**Comment by YNSTakeru** [comment]
member-task_style.css

```css
@charset "UTF-8";

body {
  margin: 0;
}

/* ヘッダー */
header {
  display: flex;
  justify-content: space-between;
  height: 3rem;
  position: fixed;
  top: 3px;

  .main-header {
    display: flex;

    svg {
      width: 5rem;
      height: 2rem;
      margin: 0 0.6rem;
    }

    h1 {
      font-size: 1.4rem;
      margin: 0.2rem 1rem 0;
    }
  }

  .change_location {
    margin: 0 0.5rem 0;
    position: inherit;
    right: 30px;
    top: 11px;

    ul {
      list-style: none;
      padding: 0;

      li {
        list-style: none;
        display: inline-block;
        margin: 0 0.5rem 0;
        font-weight: bold;

        a {
          color: black;
        }
      }
    }
  }
}

/* ページネーション */
.pagination-nav {
  position: fixed;
  bottom: 0;
  right: 20px;
  width: fit-content;
  height: 34px;
}

.pagination {
  display: inline-block;
  padding: 0;
  margin: 0;
  background-color: rgb(6, 71, 6);
  border-radius: 5px;
}

.pagination li {
  display: inline;
}

.pagination li a {
  color: white;
  float: left;
  padding: 0.3rem 0.8rem;
  text-decoration: none;
}

.pagination li a {
  color: white;
}

.pagination li a:hover {
  background-color: rgb(215, 215, 99);
}

/* タスク一覧画面 */

.task__container {
  .project__container {
    display: flex;
    justify-content: end;
    position: fixed;
    right: 5px;
    top: 30px;

    h2 {
      margin: 0;

      .project__detail {
        font-size: 1.3rem;
        font-weight: bold;
      }
    }
  }

  .transition__btn {
    position: fixed;
    top: 40px;
    left: 80px;
  }
}

.weekly__report__container {
  display: flex;
  gap: 15px;
  flex-direction: column;
  width: max-content;
  margin-top: 90px;

  .weekly__report {
    min-height: calc(((100vh - (48px + 45px) - 200px) / 4));
    background-color: rgb(6, 71, 6);
    color: white;
    display: flex;
    align-items: center;
    border-radius: 3px;

    .user__name {
      border-radius: 3px;
      font-size: 1.3rem;
      font-weight: bold;
      background-color: #095b1b;
      line-height: 6;
      border-right: 5px solid white;
      width: 100px;
      height: 130px;
      position: fixed;

      div {
        border-radius: 3px;
        text-align: center;
      }
    }

    .weekly__report__task__container {
      display: flex;
      flex-wrap: wrap;
      justify-content: flex-start;
      align-items: center;
      flex-direction: column;
      min-height: calc(((100vh - (48px + 45px) - 200px) / 4));
      border-right: solid;
      width: 180px;
      height: 130px;

      .date {
        width: inherit;
        font-size: 0.9rem;
        font-weight: bold;
        border-bottom: solid;
        margin-inline-end: auto;

        .inner_date {
          text-align: center;
          margin: 2px;

          .today {
            color: #ffee00;
          }
        }
      }

      .task {
        .title_progress {
          .task_title {
            cursor: pointer;
          }
        }
      }

      .task {
        font-size: 0.7rem;
        margin: 2px;
        width: inherit;

        .title_progress {
          display: flex;
          justify-content: space-evenly;
          margin: 1px 0 2px;
        }

        .progress-bar {
          width: 150px;
          height: 10px;
          background-color: #ddd;
          overflow: hidden;
          margin: auto;

          .progress {
            height: 100%;
            background-color: #4caf50;
            line-height: 20px;
          }

          .progress.progress-30 {
            background-color: #ec2424;
          }

          .progress.progress-60 {
            background-color: #e3d62b;
          }

          .progress.progress-80 {
            background-color: #1c2ae8;
          }

          .progress.progress-100 {
            background-color: #49df6a;
          }
        }
      }
    }
  }
}

.user__name + .weekly__report__task__container {
  margin-left: 100px;
}

```

**Comment by YNSTakeru** [comment]
popup.css
```css
ul,
li {
  margin: 0;
  padding: 0;
  list-style: none;
}

button {
  cursor: pointer;
  border: none;
  background-color: transparent;
}
button:focus {
  outline: none;
}

input {
  border: none;
  background-color: transparent;
  color: black;
}
input:focus {
  outline: none;
}

textarea {
  border: none;
  background-color: transparent;
  color: black;
  resize: none;
  outline: none;
}
textarea:focus,
textarea :hover {
  outline: none;
}

.button__container {
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 1rem;
  position: relative;
}

.register__btn {
  position: absolute;
  bottom: 20px;
  right: 20px;
}

.btn {
  display: block;
  width: -moz-fit-content;
  width: fit-content;
  min-height: 40px;
  padding: 0 20px;
  border-radius: 90px;
  border: none;
  background-color: #f6c64b;
  color: white;
  box-shadow: 6px 6px 5px 0px rgba(246, 198, 75, 0.6509803922);
  cursor: pointer;
  transition: all ease-in-out 0.2s;
}
.btn:hover,
.btn:focus {
  background-color: rgba(246, 198, 75, 0.6509803922);
  box-shadow: none;
  color: gray;
  transform: scale(0.95);
}
.btn.disabled {
  background-color: gray;
  box-shadow: none;
  cursor: not-allowed;
}
.btn.disabled:hover {
  background-color: gray;
  box-shadow: none;
  color: white;
  transform: none;
  cursor: not-allowed;
}
.btn__danger {
  background-color: #ee6d6d;
  box-shadow: 6px 6px 5px 0px rgba(238, 109, 109, 0.6509803922);
  margin-right: 20px;
}
.btn__danger:hover,
.btn__danger:focus {
  background-color: rgba(238, 109, 109, 0.6509803922);
  box-shadow: none;
  color: gray;
  transform: scale(0.95);
}
.btn__container {
  display: flex;
  justify-content: flex-end;
  align-items: flex-end;
  gap: 10px;
  position: absolute;
  bottom: 20px;
  right: 20px;
}
.btn__container .register__btn {
  position: relative;
  top: 0;
  left: auto;
}

.popup {
  visibility: hidden;
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: -moz-fit-content;
  width: fit-content;
  height: -moz-fit-content;
  height: fit-content;
  z-index: 1000;
  opacity: 0;
  transition: opacity ease-in-out 0.2s;
  gap: 10px;
  min-height: 66vh;
  max-height: 70vh;
}
.popup .parent__task__section {
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: relative;
}
.popup .parent__task__section .parent__task__input {
  cursor: pointer;
  display: block;
  border: 1px solid black;
  border-radius: 10px;
  padding: 10px 20px;
  margin-right: 20px;
  width: 100%;
}
.popup .parent__task__section .parent__task__input textarea {
  display: block;
  width: 100%;
}
.popup .parent__task__section .relative__progress__container {
  display: flex;
  flex-direction: column;
  align-items: center;
  position: absolute;
  top: 0px;
  right: 0px;
}
.popup .parent__task__section .relative__progress__container .parent__progress {
  font-size: 28px;
  -webkit-text-stroke: none;
  text-shadow: 0px 0px 3px black;
}
.popup
  .parent__task__section
  .relative__progress__container
  .parent__progress.red {
  color: #ee6d6d;
  text-shadow: 0px 0px 3px #ee6d6d;
}
.popup
  .parent__task__section
  .relative__progress__container
  .parent__progress.yellow {
  color: #ffee00;
  text-shadow: 0px 0px 3px #ffee00;
}
.popup
  .parent__task__section
  .relative__progress__container
  .parent__progress.blue {
  color: #6dcfee;
  text-shadow: 0px 0px 3px #6dcfee;
}
.popup
  .parent__task__section
  .relative__progress__container
  .parent__progress.green {
  color: #77e48f;
  text-shadow: 0px 0px 3px #77e48f;
}
.popup .popup__text {
  -webkit-text-stroke: 1px black;
  text-shadow: 0px 0px 3px black;
  color: white;
}
.popup .popup__text.parent__task {
  font-size: 28px;
}
.popup .popup__text.relation__child__task {
  font-size: 24px;
  text-shadow: 0px 0px 0px black;
}
.popup .popup__text.child__task {
  font-size: 18px;
  text-shadow: 0px 0px 0px black;
  color: white;
}
.popup .popup__text .progress__explanation__charactoer {
  font-size: 18px;
  text-shadow: 0px 0px 0px black;
  color: white;
}
.popup.popup__open {
  visibility: visible;
  display: flex;
  flex-direction: column;
  opacity: 1;
  background-color: white;
  border: 1px solid white;
  border-radius: 10px;
  padding: 20px;
  padding-right: 60px;
  min-width: 33vw;
  height: 33vh;
  gap: 10px;
}
.popup.popup__open .child__task__section {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  width: 100%;
  height: 100px;
}
.popup.popup__open .child__task__section .child__task__container {
  display: flex;
  gap: 20px;
  flex-direction: column;
  width: 100%;
  height: 29vh;
  overflow-y: scroll;
  scrollbar-width: none;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container {
  display: flex;
  gap: 3px;
  flex-direction: column;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .child__task__name__remove {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .btn__container {
  display: flex;
  flex-direction: row;
  gap: 10px;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .comment__box {
  border: 1px solid black;
  border-radius: 10px;
  margin-top: 10px;
  margin-right: 20px;
  padding: 10px 20px;
  text-shadow: none;
  opacity: 1;
  transition: all ease-in-out 0.2s;
  height: -moz-fit-content;
  height: fit-content;
  visibility: visible;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .comment__box.hidden {
  visibility: hidden;
  height: 0px;
  width: 0px;
  opacity: 0;
  margin-top: 0;
  padding: 0;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .comment__box
  .comment__textarea {
  border: none;
  width: 100%;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .comment__box
  .comment__textarea:focus {
  outline: none;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container {
  display: flex;
  gap: 10px;
  flex-direction: column;
  padding-top: 20px;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container {
  display: flex;
  gap: 10px;
  flex-direction: row;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character {
  font-size: 18px;
  text-shadow: 0px 0px 0px black;
  color: white;
  cursor: pointer;
  transition: all ease-in-out 0.2s;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character:hover,
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character.selected {
  transform: scale(1.05);
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character:hover.red,
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character.selected.red {
  color: #ee6d6d;
  text-shadow: 0px 0px 3px #ee6d6d;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character:hover.yellow,
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character.selected.yellow {
  color: #ffee00;
  text-shadow: 0px 0px 3px #ffee00;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character:hover.blue,
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character.selected.blue {
  color: #6dcfee;
  text-shadow: 0px 0px 3px #6dcfee;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character:hover.green,
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character.selected.green {
  color: #77e48f;
  text-shadow: 0px 0px 3px #77e48f;
}
.popup.popup__open
  .child__task__section
  .child__task__container
  .child__task__list__container
  .progress__container
  .progress__character__container
  .progress__character
  label {
  cursor: pointer;
}
.popup.popup__open .child__task__section .child__task__add {
  display: flex;
  width: 100%;
  height: -moz-fit-content;
  height: fit-content;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  padding-top: 5px;
  padding-bottom: 20px;
  padding-right: 0;
  padding-left: 0px;
}
.popup.popup__open .child__task__section .child__task__add .child__task__input {
  cursor: pointer;
  border: 1px solid black;
  border-radius: 10px;
  padding: 10px 20px;
  margin-right: 20px;
  width: 80%;
}
.popup.popup__open
  .child__task__section
  .child__task__add
  .child__task__input
  input {
  display: block;
  width: 100%;
}
.popup .close__btn {
  display: block;
  width: 30px;
  height: 30px;
  position: absolute;
  top: 10px;
  right: 10px;
  cursor: pointer;
}
.popup .close__btn::before {
  content: "";
  position: absolute;
  width: 100%;
  height: 2px;
  background-color: black;
  top: 50%;
  left: 0;
  transform: rotate(45deg);
}
.popup .close__btn::after {
  content: "";
  position: absolute;
  width: 100%;
  height: 2px;
  background-color: black;
  top: 50%;
  left: 0;
  transform: rotate(-45deg);
}

.cover {
  visibility: hidden;
  position: fixed;
  width: 100vw;
  height: 100vh;
  top: 0;
  left: 0;
  background-color: rgba(0, 0, 0, 0.3);
  z-index: 999;
  opacity: 0;
  transition: opacity ease-in-out 0.2s;
}
.cover.popup__open {
  visibility: visible;
  opacity: 1;
}

.hidden {
  visibility: hidden;
  height: 0px;
  width: 0px;
  opacity: 0;
  margin-top: 0;
  padding: 0;
}

.icon {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 40px;
  height: 40px;
  margin-right: 3px;
  margin-bottom: 3px;
  border-radius: 50%;
  color: white;
  cursor: pointer;
  position: relative;
  transition: all ease-in-out 0.2s;
}
.icon:hover,
.icon:focus {
  box-shadow: none;
  transform: scale(0.95);
}
.icon__add {
  background-color: #77e48f;
  box-shadow: #19af3a 3px 3px 3px;
}
.icon__add:hover,
.icon__add:focus {
  background-color: #19af3a;
}
.icon__add::before {
  content: "";
  position: absolute;
  top: 50%;
  left: 50%;
  width: 60%;
  height: 2px;
  background-color: white;
  transform: translate(-50%, -50%);
  border: 1px solid white;
}
.icon__add::after {
  content: "";
  position: absolute;
  top: 50%;
  left: 50%;
  width: 60%;
  height: 2px;
  background-color: white;
  transform: translate(-50%, -50%) rotate(90deg);
  border: 1px solid white;
}
.icon__remove {
  background-color: #ee6d6d;
  color: white;
  box-shadow: #b9490a 3px 3px 3px;
}
.icon__remove:hover,
.icon__remove:focus {
  background-color: #b9490a;
}
.icon__remove::before {
  content: "";
  position: absolute;
  top: 50%;
  left: 50%;
  width: 60%;
  height: 2px;
  background-color: white;
  transform: translate(-50%, -50%);
  border: 1px solid white;
}

.open__edit__task__btn {
  color: white;
  cursor: pointer;
  white-space: nowrap;
  transition: all ease-in-out 0.2s;
}
.open__edit__task__btn:hover {
  transform: scale(0.95);
}
.open__edit__task__btn.popup__open {
  z-index: 1001;
}

.task_progress {
  transition: all ease-in-out 0.2s;
}
.task_progress.popup__open {
  z-index: 1001;
  transform: scale(1.1);
}

.user__name.popup__open {
  position: relative;
  z-index: 1001;
}
.user__name.popup__open .popup__open {
  position: relative;
  z-index: 1001;
}

.user__name div.popup__open {
  position: relative;
  z-index: 1001;
}

.progress-bar.popup__open {
  position: relative;
  z-index: 1001;
}

.date.popup__open {
  z-index: 1001;
}

#task-edit-popup .parent__task__section .parent__task__input {
  width: 70%;
}
#task-edit-popup .parent__task__section .relative__progress__container {
  width: 20%;
} /*# sourceMappingURL=popup.css.map */
```
